ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "feeType" TEXT;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "feeAmount" DOUBLE PRECISION;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "stampDuty" DOUBLE PRECISION;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "cvt" DOUBLE PRECISION;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "totalFee" DOUBLE PRECISION;
